// src/pages/dashboard/AgenciesDashboard.tsx
import React, { useEffect, useState } from "react";
import {
  Box,
  Button,
  Typography,
  Card,
  CardContent,
  Grid,
  AppBar,
  Toolbar,
  Dialog,
  DialogContent,
  DialogActions,
  TextField,
  IconButton,
} from "@mui/material";
import { useNavigate } from "react-router-dom";
import {
  People,
  AddCircleOutline,
  Logout,
  Assessment,
  Download,
  CalendarToday,
  Close,
} from "@mui/icons-material";

import useStyles from "./styles";

const AgenciesDashboard = () => {
  const { classes } = useStyles();
  const navigate = useNavigate();

  const [activityLog, setActivityLog] = useState([
    "3/20/2025: Submitted 'AI & Data Privacy'",
    "3/21/2025: Exported team pitches",
  ]);

  const [reminderDialogOpen, setReminderDialogOpen] = useState(false);
  const [selectedPitchId, setSelectedPitchId] = useState<number | null>(null);
  const [reminderDate, setReminderDate] = useState("");

  const teamPitches = [
    {
      id: 1,
      name: "Sarah",
      client: "GreenTech Ltd",
      title: "Sustainable Energy",
      status: "Matched",
      matches: ["Forbes (85%)", "Wired (78%)"],
      followUp: "3/27/2025",
    },
    {
      id: 2,
      name: "John",
      client: "MedAI Group",
      title: "AI & Data Privacy",
      status: "Submitted",
      matches: ["TechCrunch (70%)"],
      followUp: "3/28/2025",
    },
  ];

  const currentPlan = "$150/month";

  const handleExportCSV = () => {
    const headers = ["Pitch", "Client", "Status", "Matches", "Follow-Up"];
    const rows = teamPitches.map((pitch) => [
      pitch.title,
      pitch.client,
      pitch.status,
      pitch.matches.join(" | "),
      pitch.followUp,
    ]);

    const csvContent =
      "data:text/csv;charset=utf-8," +
      [headers.join(","), ...rows.map((row) => row.join(","))].join("\n") +
      "\n\nGenerated by WriteFor.co—Submit your next pitch idea at https://media-abstract.vercel.app/ to get fresh matches!";

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "team_pitches.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setActivityLog((prev) => [
      `Exported team pitches on ${new Date().toLocaleDateString()}`,
      ...prev,
    ]);
  };

  const nextSteps = [
    "Follow up on 'AI & Data Privacy' with TechCrunch",
    "Submit another pitch!",
  ];

  // const getStatusColor = (status: string) => {
  //   return status === "Matched" ? "green" : "blue";
  // };

  const handleOpenReminderDialog = (pitchId: number) => {
    setSelectedPitchId(pitchId);
    setReminderDate("");
    setReminderDialogOpen(true);
  };

  const handleSaveReminder = () => {
    if (selectedPitchId && reminderDate) {
      setActivityLog((prevLog) => [
        ...prevLog,
        `Reminder set for pitch ID ${selectedPitchId} on ${reminderDate}`,
      ]);
      setReminderDialogOpen(false);
    }
  };

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <Box className={classes.wrapper}>
      <AppBar
        position="static"
        color="transparent"
        elevation={0}
        className={classes.appbar}
      >
        <Toolbar className={classes.toolbar}>
          <Button
            onClick={() => navigate("/")}
            className={classes.logoButton}
            disableRipple
          >
            <Typography
              variant="h6"
              style={{ fontWeight: 600 }}
              className={classes.logoText}
            >
              WriteFor.co
            </Typography>
          </Button>

          <>
            <Button
              startIcon={<Logout />}
              color="primary"
              variant="outlined"
              onClick={() => navigate("/")}
              sx={{ fontWeight: 500 }}
              className={classes.logoutButton}
            >
              LogOut
            </Button>
          </>
        </Toolbar>
      </AppBar>
      <Box className={classes.body}>
        <Grid container spacing={3} className={classes.statsSection}>
          <Grid item xs={12} sm={6} md={4} className={classes.statGrid}>
            <Card className={classes.statCard}>
              <CardContent>
                <Assessment className={classes.statIcon} />
                <Typography variant="h6">Matches</Typography>
                <Typography className={classes.statNumber}>15</Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={4} className={classes.statGrid}>
            <Card className={classes.statCard}>
              <CardContent>
                <People className={classes.statIcon} />
                <Typography variant="h6">Clients</Typography>
                <Typography className={classes.statNumber}>3</Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        <Box sx={{ textAlign: "center", my: 4 }} className={classes.buttonRow}>
          <Button
            variant="contained"
            //color="primary"
            size="large"
            className={classes.newPitchBtn}
            onClick={() => navigate("/onboarding")}
          >
            New Client Pitch
          </Button>
        </Box>

        {(currentPlan === "$150/month" || currentPlan === "$250/month") && (
          <Button
            variant="outlined"
            color="secondary"
            startIcon={<AddCircleOutline />}
            className={classes.addUserBtn}
            onClick={() => alert("Redirect to Add User functionality")}
          >
            Add User
          </Button>
        )}

        <Box mb={3} className={classes.nextStepsSection}>
          <Typography variant="h6" className={classes.sectionHeader}>
            Next Steps
          </Typography>
          {nextSteps.map((step, i) => (
            <Typography key={i} variant="body1">
              • {step}
            </Typography>
          ))}
        </Box>

        <Box className={classes.sectionHeaderRow}>
          <Typography variant="h6" className={classes.sectionHeader}>
            Team Pitches
          </Typography>
          <Button
            startIcon={<Download />}
            variant="outlined"
            size="small"
            className={classes.exportButton}
            onClick={handleExportCSV}
          >
            Export Pitches
          </Button>
        </Box>

        {teamPitches.map((pitch) => (
          // <Card key={pitch.id} className={classes.pitchCard}>
          //   <CardContent>
          //     <Box display="flex" alignItems="center" gap={1}>
          //       <Tooltip title={pitch.status}>
          //         <Circle
          //           fontSize="small"
          //           style={{ color: getStatusColor(pitch.status) }}
          //         />
          //       </Tooltip>
          //       <Typography variant="h6" className={classes.pitchTitle}>
          //         {pitch.name}: {pitch.title}
          //       </Typography>
          //     </Box>
          //     <Typography variant="body2">Client: {pitch.client}</Typography>
          //     <Typography variant="body2">
          //       Matches: {pitch.matches.join(", ")}
          //     </Typography>
          //     <Button
          //       size="small"
          //       onClick={() => navigate(`/results/${pitch.id}`)}
          //       sx={{ textTransform: "none", mt: 1 }}
          //     >
          //       See Matches
          //     </Button>
          //     <Typography variant="body2" mt={1}>
          //       Follow-Up: {pitch.followUp}
          //     </Typography>
          //     <Button
          //       size="small"
          //       onClick={() => alert("Open follow-up date picker")}
          //       sx={{ textTransform: "none", mt: 1 }}
          //     >
          //       Set Reminder
          //     </Button>
          //   </CardContent>
          // </Card>

          <Card key={pitch.id} className={classes.pitchCard}>
            <CardContent>
              <Box
                display="flex"
                justifyContent="space-between"
                alignItems="center"
              >
                <Typography variant="h6" className={classes.pitchTitle}>
                  {pitch.name}: {pitch.title}
                </Typography>
                <Box display="flex" alignItems="center">
                  <Box
                    sx={{
                      width: 10,
                      height: 10,
                      borderRadius: "50%",
                      backgroundColor:
                        pitch.status === "Matched" ? "green" : "blue",
                      marginRight: 1,
                    }}
                  />
                  <Typography variant="body2">{pitch.status}</Typography>
                </Box>
              </Box>
              <Typography variant="body2" color="textSecondary">
                Client: {pitch.client}
              </Typography>
              <Typography variant="body2">
                Matches: {pitch.matches.join(", ")} |{" "}
                <Button size="small" onClick={() => navigate("/results")}>
                  See Matches
                </Button>
              </Typography>
              <Typography variant="body2">
                Follow-Up: {pitch.followUp} |{" "}
                <Button
                  size="small"
                  onClick={() => handleOpenReminderDialog(pitch.id)}
                >
                  Set Reminder
                </Button>
              </Typography>
            </CardContent>
          </Card>
        ))}

        {/* Activity Timeline Placeholder */}
        <Box mt={4}>
          <Typography variant="h6" className={classes.sectionHeader}>
            Activity
          </Typography>
          <Card className={classes.pitchCard}>
            <CardContent>
              {activityLog.map((entry, index) => (
                <Typography key={index} variant="body2" gutterBottom>
                  • {entry}
                </Typography>
              ))}
            </CardContent>
          </Card>
          {/* <Timeline>
            {activityLog.map((activity, i) => (
              <TimelineItem key={i}>
                <TimelineSeparator>
                  <TimelineDot color="primary" />
                </TimelineSeparator>
                <TimelineContent>{activity}</TimelineContent>
              </TimelineItem>
            ))}
          </Timeline> */}
        </Box>

        <Dialog
          open={reminderDialogOpen}
          onClose={() => setReminderDialogOpen(false)}
          maxWidth="xs"
          fullWidth
          PaperProps={{
            sx: {
              borderRadius: 3,
              p: 2,
              boxShadow: 10,
              background: "#fff",
            },
          }}
        >
          <Box
            display="flex"
            justifyContent="space-between"
            alignItems="center"
            px={2}
            pt={1}
          >
            <Box display="flex" alignItems="center" sx={{ margin: "10px" }}>
              <CalendarToday sx={{ mr: 1, color: "primary.main" }} />
              <Typography variant="h6" fontWeight={600}>
                Set Follow-Up Reminder
              </Typography>
            </Box>
            <IconButton
              onClick={() => setReminderDialogOpen(false)}
              size="small"
            >
              <Close />
            </IconButton>
          </Box>

          <DialogContent sx={{ mt: 2, marginBottom: "15px" }}>
            <Typography
              variant="body2"
              color="text.secondary"
              mb={1}
              sx={{ margin: "15px" }}
            >
              Choose the date you'd like to be reminded to follow up.
            </Typography>

            <TextField
              label="Reminder Date"
              type="date"
              value={reminderDate}
              onChange={(e) => setReminderDate(e.target.value)}
              InputLabelProps={{ shrink: true }}
              fullWidth
              InputProps={{
                sx: {
                  borderRadius: 2,
                  backgroundColor: "#f9f9f9",
                },
              }}
            />
          </DialogContent>

          <DialogActions sx={{ px: 3, pb: 2 }}>
            <Button
              onClick={() => setReminderDialogOpen(false)}
              variant="text"
              sx={{ textTransform: "none", fontWeight: 500 }}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSaveReminder}
              variant="contained"
              disabled={!reminderDate}
              sx={{
                textTransform: "none",
                borderRadius: 2,
                px: 3,
                fontWeight: 600,
                boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
              }}
            >
              Save Reminder
            </Button>
          </DialogActions>
        </Dialog>
      </Box>
    </Box>
  );
};

export default AgenciesDashboard;
