// src/pages/dashboard/dashboardStyles.ts
import { makeStyles } from "tss-react/mui";

const useStyles = makeStyles()((theme) => ({
  wrapper: {
    display: "flex",
    background: "#f8fafc",
    paddingTop: theme.spacing(8),
    paddingBottom: theme.spacing(10),
    [theme.breakpoints.down("sm")]: {
      padding: theme.spacing(2, 0),
      paddingBottom: theme.spacing(6),
    },
  },
  appbar: {
    display: "flex",
    height: "64px",
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ffffff",
    zIndex: 1200,
    borderBottom: "1px solid rgba(0, 0, 0, 0.08)",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
    backdropFilter: "blur(8px)",
    borderRadius: "0 0 12px 12px",
    transition: "all 0.3s ease",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    padding: theme.spacing(0, 4),
    [theme.breakpoints.down("sm")]: {
      padding: theme.spacing(0, 2),
    },
  },
  logoButton: {
    textTransform: "none",
    padding: 0,
    minWidth: "auto",
    transition: "all 0.2s ease",
  },
  logoText: {
    fontWeight: 600,
    fontSize: "1.4rem",
    color: "#1a1a1a",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "#2563eb",
    },
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(2),
  },
  prioritySupportChip: {
    backgroundColor: "rgba(37, 99, 235, 0.08)",
    borderColor: "#2563eb",
    "& .MuiChip-icon": {
      color: "#2563eb",
    },
  },
  logoutButton: {
    fontWeight: 500,
    width: "110px",
    height: "38px",
    textTransform: "none",
    borderRadius: "6px",
    border: "1px solid #e0e0e0",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#f1f5f9",
      borderColor: "#2563eb",
      color: "#2563eb",
    },
    [theme.breakpoints.down("sm")]: {
      width: "90px",
      height: "34px",
    },
  },
  body: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
    padding: theme.spacing(3, 2),
    paddingTop: "80px",
    backgroundColor: "#f8fafc",
    position: "relative",
    minHeight: "calc(100vh - 64px)",
    [theme.breakpoints.down("sm")]: {
      padding: theme.spacing(2, 1),
      paddingTop: "76px",
    },
  },
  bodyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing(4),
    marginTop: theme.spacing(2),
    padding: theme.spacing(3),
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    position: "relative",
    overflow: "hidden",
    border: "1px solid rgba(0, 0, 0, 0.04)",
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      padding: theme.spacing(2),
      marginBottom: theme.spacing(3),
    },
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(2),
  },
  avatar: {
    width: 48,
    height: 48,
    border: "2px solid #2563eb",
  },
  welcomeText: {
    fontWeight: 700,
    fontSize: "2.8rem",
    color: "#1a1a1a",
    margin: 5,
    position: "relative",
    zIndex: 1,
    letterSpacing: "-0.02em",
    [theme.breakpoints.down("sm")]: {
      fontSize: "1.8rem",
    },
  },
  userStats: {
    display: "flex",
    gap: theme.spacing(3),
    position: "relative",
    zIndex: 1,
    [theme.breakpoints.down("sm")]: {
      marginTop: theme.spacing(2),
      gap: theme.spacing(2),
      flexDirection: "column",
      alignItems: "stretch",
      width: "100%",
    },
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: theme.spacing(1.5, 2),
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    transition: "all 0.3s ease",
    border: "1px solid rgba(0, 0, 0, 0.04)",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 8px 32px rgba(37, 99, 235, 0.1)",
    },
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      padding: theme.spacing(1.5),
    },
  },
  statValue: {
    fontWeight: 600,
    fontSize: "1.2rem",
    color: "#2563eb",
  },
  statLabel: {
    fontSize: "0.875rem",
    color: "#64748b",
    fontWeight: 500,
  },
  newPitchButton: {
    padding: theme.spacing(1.2, 3.5),
    fontSize: "1.1rem",
    fontWeight: 600,
    borderRadius: "10px",
    backgroundColor: "#2563eb",
    textTransform: "none",
    color: "#fff",
    boxShadow: "0 2px 8px rgba(37, 99, 235, 0.2)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    "&:hover": {
      backgroundColor: "#1d4ed8",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(37, 99, 235, 0.3)",
    },
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      marginTop: theme.spacing(2),
      fontSize: "1rem",
      padding: theme.spacing(1, 3),
    },
  },
  divider: {
    margin: theme.spacing(3, 0),
    borderColor: "rgba(0, 0, 0, 0.08)",
  },
  dashboardLayout: {
    display: "grid",
    gridTemplateColumns: "1fr 300px",
    gap: theme.spacing(3),
    width: "100%",
    alignItems: "start",
    position: "relative",
    minHeight: "calc(100vh - 140px)",
    marginTop: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
      minHeight: "auto",
    },
  },
  mainContent: {
    width: "100%",
  },
  buttonContainer: {
    marginBottom: theme.spacing(3),
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    fontWeight: 600,
    color: "#1a1a1a",
  },
  pitchGrid: {
    marginBottom: theme.spacing(4),
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: theme.spacing(3),
    [theme.breakpoints.down("sm")]: {
      gridTemplateColumns: "1fr",
    },
  },
  pitchCard: {
    height: "100%",
    background: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    transition: "all 0.3s ease",
    border: "1px solid rgba(0, 0, 0, 0.04)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 8px 32px rgba(37, 99, 235, 0.1)",
    },
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "3px",
      background: "linear-gradient(90deg, #2563eb, #1d4ed8)",
      opacity: 0,
      transition: "opacity 0.3s ease",
    },
    "&:hover::before": {
      opacity: 1,
    },
  },
  pitchCardContent: {
    padding: theme.spacing(2.5),
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
    position: "relative",
    zIndex: 1,
  },
  pitchHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
  pitchTitle: {
    fontWeight: 600,
    fontSize: "1.1rem",
    color: "#1a1a1a",
    flex: 1,
    marginRight: theme.spacing(2),
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    minWidth: 0,
    lineHeight: 1.4,
  },
  pitchStatus: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(1),
    padding: theme.spacing(0.5, 1),
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: 500,
    whiteSpace: "nowrap",
    flexShrink: 0,
    background: "#2563eb",
    color: "#fff",
    "&.submitted": {
      background: "#2563eb",
      color: "#fff",
    },
    "&.matched": {
      background: "#10b981",
      color: "#fff",
    },
    "&.accepted": {
      background: "#059669",
      color: "#fff",
    },
    "&.rejected": {
      background: "#dc2626",
      color: "#fff",
    },
    "&.followedup": {
      background: "#f59e0b",
      color: "#fff",
    },
  },
  pitchStatusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    marginRight: theme.spacing(1),
    backgroundColor: "#fff",
  },
  pitchMatches: {
    marginTop: "auto",
    paddingTop: theme.spacing(2),
    borderTop: "1px solid rgba(0,0,0,0.08)",
    background: "rgba(37, 99, 235, 0.02)",
    borderRadius: "8px",
    padding: theme.spacing(1.5),
  },
  matchList: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.5),
    marginBottom: theme.spacing(2),
  },
  matchItem: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    fontSize: "0.875rem",
    color: "#64748b",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: theme.spacing(0.5, 1),
    borderRadius: "6px",
    background: "rgba(255, 255, 255, 0.5)",
    transition: "all 0.2s ease",
    "&:hover": {
      background: "rgba(255, 255, 255, 0.8)",
      transform: "translateX(4px)",
    },
  },
  pitchActions: {
    display: "flex",
    gap: theme.spacing(1),
    marginTop: "auto",
    "& button": {
      flex: 1,
      minWidth: "100px",
      borderRadius: "8px",
      textTransform: "none",
      fontWeight: 500,
      padding: theme.spacing(0.75, 1.5),
      transition: "all 0.2s ease",
      "&.primary": {
        background: "rgba(37, 99, 235, 0.1)",
        color: "#2563eb",
        "&:hover": {
          background: "rgba(37, 99, 235, 0.2)",
          transform: "translateY(-2px)",
        },
      },
      "&.secondary": {
        background: "rgba(0, 0, 0, 0.05)",
        color: "#64748b",
        "&:hover": {
          background: "rgba(0, 0, 0, 0.1)",
          transform: "translateY(-2px)",
        },
      },
    },
  },
  activitySidebar: {
    position: "sticky",
    top: "80px",
    height: "calc(100vh - 140px)",
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    overflow: "hidden",
    transition: "all 0.3s ease",
    border: "1px solid rgba(0, 0, 0, 0.04)",
    display: "flex",
    flexDirection: "column",
    alignSelf: "flex-start",
    "&:hover": {
      boxShadow: "0 8px 32px rgba(37, 99, 235, 0.1)",
    },
    [theme.breakpoints.down("md")]: {
      position: "relative",
      top: 0,
      height: "auto",
      marginBottom: theme.spacing(3),
      order: -1,
    },
  },
  activityHeader: {
    background: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    color: "#fff",
    padding: theme.spacing(2.5, 2),
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1.5),
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    position: "sticky",
    top: 0,
    zIndex: 1,
    [theme.breakpoints.down("md")]: {
      position: "relative",
    },
  },
  activityContent: {
    padding: theme.spacing(2),
    flex: 1,
    overflowY: "auto",
    height: "calc(100vh - 240px)",
    "&::-webkit-scrollbar": {
      width: "6px",
    },
    "&::-webkit-scrollbar-track": {
      background: "#f1f5f9",
      borderRadius: "3px",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#cbd5e1",
      borderRadius: "3px",
      "&:hover": {
        background: "#94a3b8",
      },
    },
    [theme.breakpoints.down("md")]: {
      height: "auto",
      maxHeight: "300px",
    },
  },
  noActivity: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: theme.spacing(4),
    color: "#94a3b8",
  },
  activityItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: theme.spacing(2),
    padding: theme.spacing(2),
    borderBottom: "1px solid rgba(0, 0, 0, 0.08)",
  },
  activityIcon: {
    color: "#2563eb",
  },
  activityText: {
    flex: 1,
    "& .action": {
      fontWeight: 500,
      marginBottom: theme.spacing(0.5),
    },
    "& .timestamp": {
      display: "flex",
      alignItems: "center",
      gap: theme.spacing(0.5),
      color: "#64748b",
      fontSize: "0.75rem",
    },
  },
  nextStepsSection: {
    marginTop: theme.spacing(4),
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    marginBottom: theme.spacing(2),
    fontWeight: 600,
  },
  nextStepItem: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(2),
    padding: theme.spacing(2),
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    marginBottom: theme.spacing(2),
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 8px 32px rgba(37, 99, 235, 0.1)",
    },
  },
  nextStepIcon: {
    color: "#2563eb",
  },
  nextStepContent: {
    flex: 1,
  },
  nextStepTitle: {
    fontWeight: 600,
    marginBottom: theme.spacing(0.5),
  },
  nextStepDescription: {
    color: "#64748b",
    fontSize: "0.875rem",
  },
  nextStepArrow: {
    color: "#94a3b8",
  },
  createPitchContainer: {
    display: "flex",
    justifyContent: "center",
    marginTop: theme.spacing(4),
  },
  createPitchButton: {
    padding: theme.spacing(1.5, 4),
    fontSize: "1.1rem",
    fontWeight: 600,
    borderRadius: "10px",
    textTransform: "none",
    background: "linear-gradient(45deg, #2563eb 30%, #1d4ed8 90%)",
    boxShadow: "0 4px 12px rgba(37, 99, 235, 0.2)",
    color: "#ffffff",
    position: "relative",
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      background:
        "linear-gradient(45deg, transparent, rgba(255, 255, 255, 0.2), transparent)",
      transform: "translateX(-100%)",
      transition: "transform 0.6s ease",
    },
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 16px rgba(37, 99, 235, 0.3)",
      background: "linear-gradient(45deg, #1d4ed8 30%, #2563eb 90%)",
      "&::before": {
        transform: "translateX(100%)",
      },
    },
    [theme.breakpoints.down("sm")]: {
      padding: theme.spacing(1, 3),
      fontSize: "1rem",
    },
  },
  bulkActions: {
    display: "flex",
    gap: theme.spacing(2),
    marginBottom: theme.spacing(3),
  },
  pitchCheckbox: {
    padding: 0,
    marginRight: theme.spacing(1),
  },
  pitchActionButton: {
    textTransform: "none",
    fontWeight: 500,
    "&.primary": {
      color: theme.palette.primary.main,
      "&:hover": {
        backgroundColor: "rgba(37, 99, 235, 0.08)",
      },
    },
    "&.secondary": {
      color: theme.palette.text.secondary,
      "&:hover": {
        backgroundColor: "rgba(0, 0, 0, 0.04)",
      },
    },
  },
  premiumInsights: {
    marginTop: theme.spacing(4),
  },
  insightsCard: {
    backgroundColor: "#f8fafc",
    borderRadius: "12px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
  },
  insightsTitle: {
    fontWeight: 600,
    color: theme.palette.text.primary,
    marginBottom: theme.spacing(1),
  },
  savedOutletsSection: {
    marginTop: theme.spacing(4),
    padding: theme.spacing(3),
    background: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    transition: "all 0.3s ease",
    border: "1px solid rgba(0, 0, 0, 0.04)",
    "&:hover": {
      boxShadow: "0 8px 32px rgba(37, 99, 235, 0.1)",
    },
  },
  savedOutletsTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    marginBottom: theme.spacing(3),
    color: "#1a1a1a",
    letterSpacing: "-0.02em",
    [theme.breakpoints.down("sm")]: {
      fontSize: "1.2rem",
      marginBottom: theme.spacing(2),
    },
  },
  savedOutletsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: theme.spacing(3),
    marginTop: theme.spacing(3),
  },
  savedPitchCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: theme.spacing(2),
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(0, 0, 0, 0.04)",
  },
  savedPitchHeader: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    marginBottom: theme.spacing(2),
  },
  savedPitchIcon: {
    color: "#2563eb",
  },
  savedPitchTitle: {
    flex: 1,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
    lineHeight: 1.4,
  },
  savedPitchDropdown: {
    transition: "transform 0.2s ease",
    "&.expanded": {
      transform: "rotate(180deg)",
    },
  },
  savedOutletsList: {
    display: "none",
    "&.expanded": {
      display: "block",
    },
  },
  savedOutletItem: {
    padding: theme.spacing(1),
    "&:hover": {
      backgroundColor: "#f8fafc",
      borderRadius: "4px",
    },
  },
  savedOutletName: {
    cursor: "pointer",
    color: "#2563eb",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  moreButton: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    cursor: "pointer",
    padding: theme.spacing(1),
    marginTop: theme.spacing(1),
    color: "#2563eb",
  },
  moreButtonText: {
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  moreButtonIcon: {
    transition: "transform 0.2s ease",
    "&.expanded": {
      transform: "rotate(180deg)",
    },
  },
  emptyStateCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: theme.spacing(4),
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(0, 0, 0, 0.04)",
  },
  emptyStateIcon: {
    fontSize: "3rem",
    color: "#94a3b8",
    marginBottom: theme.spacing(2),
  },
  emptyStateText: {
    textAlign: "center",
    color: "#64748b",
  },
  savedDate: {
    fontSize: "0.875rem",
    color: "#64748b",
    marginTop: theme.spacing(1),
  },
  teamMembersButton: {
    padding: theme.spacing(1.2, 3.5),
    fontSize: "1.1rem",
    fontWeight: 600,
    borderRadius: "10px",
    textTransform: "none",
    color: "#2563eb",
    borderColor: "#2563eb",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    "&:hover": {
      backgroundColor: "rgba(37, 99, 235, 0.1)",
      transform: "translateY(-2px)",
    },
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      marginTop: theme.spacing(2),
      fontSize: "1rem",
      padding: theme.spacing(1, 3),
    },
  },
}));

export default useStyles;
